apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sysdig-deploy
  namespace: argocd
spec:
  project: default
  destination:
    namespace: sysdig-agent
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: 'https://github.com/yoshiouchi/argocd-gke'
    targetRevision: main
    helm:
      valueFiles:
      - apps/sysdig-deploy/clustershield-values.yaml
  ignoreDifferences:
  - name: sysdig-clustershield
    kind: Secret
    jsonPointers:
    - /data/sysdig-cluster-nats-password
  - name: sysdig-clustershield-tls-certs
    kind: Secret
    jsonPointers:
    - /data
  - name: sysdig-deploy-clustershield-audit
    kind: ValidatingWebhookConfiguration
    jqPathExpressions:
    - .webhooks[].clientConfig.caBundle
  syncPolicy:
    automated: null
    syncOptions:
      - CreateNamespace=true